import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import '../cli_colors.dart';
import 'asset.dart' as asset_reader;
import 'asset.dart';

/// Generator for assets.g.dart file
class AssetsGenerator {

  AssetsGenerator({
    required this.compress,
    required this.svgMinify,
    required this.encryptionMethod,
    required this.chunkSize,
    this.maxMemoryFileSize = 10 * 1024 * 1024, // 10MB default
  });
  final bool compress;
  final bool svgMinify;
  final EncryptionMethod encryptionMethod;
  final int chunkSize;
  final int maxMemoryFileSize; // Files larger than this will use streaming

  // Cache for expensive operations
  static final Map<String, List<int>> _compressionCache = <String, List<int>>{};
  static final Map<String, String> _svgMinifyCache = <String, String>{};

  Future<String> generate() async {
    // Use the actual file system path to find assets
    final assetsDir = p.join(Directory.current.path, 'assets');

    CliLogger.debug('Looking for assets in: $assetsDir');
    final assets = asset_reader.AssetReader.scanAssetsDirectory(assetsDir);
    // Sort assets by size for optimal processing (small files first for faster feedback)
    final sortedAssets = List<asset_reader.AssetFile>.from(assets)
      ..sort((a, b) {
        final aSize = File(a.path).lengthSync();
        final bSize = File(b.path).lengthSync();
        return aSize.compareTo(bSize); // Small files first
      });

    CliLogger.debug('Processing ${sortedAssets.length} assets (sorted by size)');

    // Parallelize asset processing for better performance
    final processedAssets = await Future.wait(
      sortedAssets.map(_processAsset),
      eagerError: true,
    );

    // Build output code
    final buffer = StringBuffer();
    
    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// This file is automatically generated by env_builder_cli');
    buffer.writeln('// ignore_for_file: avoid_print');
    buffer.writeln('');
    buffer.writeln("import 'dart:convert';");
    buffer.writeln("import 'dart:typed_data';");
    if (encryptionMethod == EncryptionMethod.aes) {
      buffer.writeln("import 'package:encrypt/encrypt.dart' as encrypt;");
    }
    buffer.writeln('');

    // Generate code for each asset (sequential, as order may matter for output)
    for (var i = 0; i < sortedAssets.length; i++) {
      final asset = sortedAssets[i];
      final encryptedAsset = processedAssets[i];

      try {
        // Generate key constant
        buffer.writeln(
          'const List<int> _assetkey${asset.variableName} = <int>${_formatByteList(encryptedAsset.key)};',
        );

        // Generate data constant
        buffer.writeln(
          'const List<int> assetdata${asset.variableName} = <int>${_formatByteList(encryptedAsset.data)};',
        );

        // Generate decrypted asset getter
        if (asset.type == asset_reader.AssetType.svg) {
          buffer.writeln(
            'String get decrypted${asset.variableName} => String.fromCharCodes(${_generateDecryptCall(asset.variableName, encryptionMethod)});',
          );
        } else {
          buffer.writeln(
            'Uint8List get decrypted${asset.variableName} => Uint8List.fromList(${_generateDecryptCall(asset.variableName, encryptionMethod)});',
          );
        }

        buffer.writeln();
      } catch (e) {
        CliLogger.error('Error generating code for asset ${asset.path}: $e');
        // Continue with other assets
      }
    }

    // Generate utility methods
    _generateUtilityMethods(buffer, encryptionMethod);
    
    return buffer.toString();
  }

  /// Get cache statistics for monitoring and debugging
  static Map<String, int> getCacheStats() => {
      'compressionCacheSize': _compressionCache.length,
      'svgMinifyCacheSize': _svgMinifyCache.length,
    };

  Future<EncryptedAsset> _processAsset(asset_reader.AssetFile asset) async {
    final bytes = await _readAssetBytes(asset);

    // Process based on type
    List<int> processedBytes;
    if (asset.type == asset_reader.AssetType.svg) {
      // For SVG files, ensure proper UTF-8 encoding
      final normalizedSvgBytes = _normalizeSvgEncoding(bytes);
      final svgContent = utf8.decode(normalizedSvgBytes);

      if (svgMinify) {
        // Use cache for SVG minification
        final cacheKey = 'svg_minify_${asset.path.hashCode}_${svgContent.hashCode}';
        if (_svgMinifyCache.containsKey(cacheKey)) {
          processedBytes = utf8.encode(_svgMinifyCache[cacheKey]!);
        } else {
          final minified = asset_reader.AssetReader.minifySvg(svgContent);
          _svgMinifyCache[cacheKey] = minified;
          processedBytes = utf8.encode(minified);
        }
      } else {
        processedBytes = normalizedSvgBytes;
      }
    } else if ((asset.type == asset_reader.AssetType.image) && compress) {
      // Use cache for image compression
      final cacheKey = 'compress_${asset.path.hashCode}_${bytes.length}';
      if (_compressionCache.containsKey(cacheKey)) {
        processedBytes = _compressionCache[cacheKey]!;
      } else {
        processedBytes = asset_reader.AssetReader.compressImage(
          bytes,
          asset.extension,
        );
        _compressionCache[cacheKey] = processedBytes;
      }
    } else if (asset.type == asset_reader.AssetType.video) {
      // Videos are kept as raw binary data (no compression available)
      processedBytes = bytes;
    } else {
      // Other binary assets (like unknown types) are kept as raw bytes
      processedBytes = bytes;
    }

    // Encrypt
    return AssetCrypto.encryptAsset(processedBytes, encryptionMethod);
  }

  Future<List<int>> _readAssetBytes(asset_reader.AssetFile asset) async {
    final file = File(asset.path);
    final fileSize = await file.length();

    // For large files, use streaming to avoid loading everything into memory
    if (fileSize > maxMemoryFileSize) {
      return _readAssetBytesStreaming(asset);
    }

    // For smaller files, use the existing chunked approach
    final bytes = <int>[];
    await asset_reader.AssetReader.readAssetInChunks(
      asset.path,
      chunkSize: chunkSize * 1024,
    ).forEach(bytes.addAll);
    return bytes;
  }

  /// Stream-based reading for large files to minimize memory usage
  Future<List<int>> _readAssetBytesStreaming(asset_reader.AssetFile asset) async {
    final file = File(asset.path);
    final bytes = <int>[];

    // Use streaming to avoid loading everything into memory at once
    // Default chunk size is controlled by the system (typically 64KB)
    final stream = file.openRead();

    await for (final chunk in stream) {
      bytes.addAll(chunk);
      // Yield control to avoid blocking for too long on very large files
      if (bytes.length % (1024 * 1024) == 0) { // Every 1MB
        await Future.delayed(Duration.zero);
      }
    }

    return bytes;
  }

  /// Normalize SVG encoding to UTF-8
  ///
  /// Handles different text encodings that SVG files might have:
  /// - UTF-16 with BOM (common on Windows)
  /// - UTF-8 (standard for web)
  List<int> _normalizeSvgEncoding(List<int> bytes) {
    // Check for UTF-16 LE BOM (0xFF 0xFE)
    if (bytes.length >= 2 && bytes[0] == 0xFF && bytes[1] == 0xFE) {
      // Remove BOM and convert UTF-16 LE to string
      final utf16Bytes = bytes.sublist(2);
      final content = _decodeUtf16LE(utf16Bytes);
      return utf8.encode(content);
    }

    // Check for UTF-16 BE BOM (0xFE 0xFF)
    if (bytes.length >= 2 && bytes[0] == 0xFE && bytes[1] == 0xFF) {
      // Remove BOM and convert UTF-16 BE to string
      final utf16Bytes = bytes.sublist(2);
      final content = _decodeUtf16BE(utf16Bytes);
      return utf8.encode(content);
    }

    // Try to decode as UTF-8, if it fails, assume it's already UTF-8 bytes
    try {
      utf8.decode(bytes);
      return bytes; // Already valid UTF-8
    } catch (e) {
      // If UTF-8 decoding fails, try to interpret as Latin-1 and re-encode as UTF-8
      try {
        final content = String.fromCharCodes(bytes);
        return utf8.encode(content);
      } catch (e) {
        // Last resort: return as-is
        return bytes;
      }
    }
  }

  /// Decode UTF-16 LE bytes to string
  String _decodeUtf16LE(List<int> bytes) {
    final codeUnits = <int>[];
    for (var i = 0; i < bytes.length; i += 2) {
      if (i + 1 < bytes.length) {
        // Little-endian: low byte first
        final low = bytes[i];
        final high = bytes[i + 1];
        final codeUnit = (high << 8) | low;
        codeUnits.add(codeUnit);
      }
    }
    return String.fromCharCodes(codeUnits);
  }

  /// Decode UTF-16 BE bytes to string
  String _decodeUtf16BE(List<int> bytes) {
    final codeUnits = <int>[];
    for (var i = 0; i < bytes.length; i += 2) {
      if (i + 1 < bytes.length) {
        // Big-endian: high byte first
        final high = bytes[i];
        final low = bytes[i + 1];
        final codeUnit = (high << 8) | low;
        codeUnits.add(codeUnit);
      }
    }
    return String.fromCharCodes(codeUnits);
  }

  String _formatByteList(List<int> bytes) {
    if (bytes.length <= 100) {
      // Small lists can be formatted on one line
      return '[${bytes.join(', ')}]';
    } else {
      // Large lists should be formatted with line breaks for readability
      final buffer = StringBuffer('[\n');
      for (var i = 0; i < bytes.length; i += 20) {
        final end = (i + 20 < bytes.length) ? i + 20 : bytes.length;
        buffer.write('  ${bytes.sublist(i, end).join(', ')},\n');
      }
      buffer.write(']');
      return buffer.toString();
    }
  }

  String _generateDecryptCall(String variableName, EncryptionMethod method) {
    switch (method) {
      case EncryptionMethod.xor:
        return '_decryptXor(_assetkey$variableName, assetdata$variableName)';
      case EncryptionMethod.aes:
        return '_decryptAes(_assetkey$variableName, assetdata$variableName)';
    }
  }

  void _generateUtilityMethods(StringBuffer buffer, EncryptionMethod method) {
    switch (method) {
      case EncryptionMethod.xor:
        buffer.writeln(
          'List<int> _decryptXor(List<int> key, List<int> data) {',
        );
        buffer.writeln('  final decrypted = <int>[];');
        buffer.writeln('  for (var i = 0; i < data.length; i++) {');
        buffer.writeln('    decrypted.add(data[i] ^ key[i % key.length]);');
        buffer.writeln('  }');
        buffer.writeln('  return decrypted;');
        buffer.writeln('}');
        break;

      case EncryptionMethod.aes:
        buffer.writeln(
          'List<int> _decryptAes(List<int> key, List<int> data) {',
        );
        buffer.writeln('  final keyObj = encrypt.Key(Uint8List.fromList(key));');
        buffer.writeln('  final iv = encrypt.IV(Uint8List.fromList(data.sublist(0, 16)));');
        buffer.writeln('  final encryptedData = encrypt.Encrypted(Uint8List.fromList(data.sublist(16)));');
        buffer.writeln('  final encrypter = encrypt.Encrypter(encrypt.AES(keyObj));');
        buffer.writeln('  final decrypted = encrypter.decryptBytes(encryptedData, iv: iv);');
        buffer.writeln('  return decrypted;');
        buffer.writeln('}');
        break;
    }
  }
}
