name: relax_image_picker
description: "A powerful, WhatsApp-like media picker for Flutter"
version: 1.0.0
resolution: workspace

repository: https://github.com/KalybosPro/relax-tech/tree/main/packages/relax_image_picker
issue_tracker: https://github.com/KalybosPro/relax-tech/issues

environment:
  sdk: ^3.11.0

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  photo_manager: ^3.9.0
  file_picker: ^11.0.2
  camera: ^0.12.0+1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
