// ignore_for_file: avoid_print

/// Configuration constants for the environment builder
///
/// Centralizes mappings between environment types (development, production, staging)
/// and their corresponding abbreviations, class names, and file names.
/// These mappings are used throughout the CLI to generate consistent artifacts.
class EnvConfig {
  static const String defaultDescription =
      'A very good package generated by Env Builder CLI for environment variables';
  static const String defaultVersion = '1.0.0';
  static const String defaultSdkVersion = '^3.8.1';
  static const String defaultFlutterVersion = '>=1.17.0';

  /// Environment mappings
  static const Map<String, String> environmentMappings = {
    'development': 'dev',
    'production': 'prod',
    'staging': 'stg',
  };

  /// Class name mappings
  static const Map<String, String> classNameMappings = {
    'development': 'EnvDev',
    'production': 'EnvProd',
    'staging': 'EnvStg',
  };

  /// file name mappings
  static const Map<String, String> fileNameMappings = {
    'development': 'env.dev.dart',
    'production': 'env.prod.dart',
    'staging': 'env.stg.dart',
  };
}
