import '../analyzer/infra_types.dart';
import '../models/quality_models.dart';

/// Generates a new UseCase file from a [UseCaseCandidate].
///
/// The output mirrors the specification's template: infrastructure
/// dependencies injected via the constructor and an `execute(...)` method whose
/// signature matches the business function. When the original method's primary
/// infrastructure call can be recovered from the AST, `execute` reconstructs it
/// (e.g. `return repository.login(email, password);`); otherwise it emits a
/// `TODO` + `UnimplementedError()`.
///
/// This only ever produces a **new file** — it never rewrites the source
/// controller or its call sites (that transformation is intentionally left to a
/// reviewed, opt-in step, per the spec's safe-fix whitelist). Domain-type
/// imports can't be resolved from the syntactic AST, so a `TODO` header lists
/// what to add.
class UseCaseGenerator {
  GeneratedUseCase generate(UseCaseCandidate candidate) {
    final fn = candidate.businessFunction;
    final className = candidate.suggestedClassName;
    final deps = _infraDependencies(fn);
    final owner = fn.className ?? _pascal(fn.name);

    final buffer = StringBuffer()
      ..writeln('// GENERATED by `relax quality --generate-usecases`.')
      ..writeln('// Add the imports for the referenced domain types')
      ..writeln('// (${_referencedTypes(fn, deps).join(', ')}) before use.')
      ..writeln()
      ..writeln('class $className {');

    // Constructor + injected dependencies.
    if (deps.isNotEmpty) {
      final ctorParams = deps.map((d) => 'this.${d.name}').join(', ');
      buffer.writeln('  $className($ctorParams);');
      for (final dep in deps) {
        buffer.writeln('  final ${dep.type} ${dep.name};');
      }
      buffer.writeln();
    }

    // execute() signature mirrors the business function.
    final params = fn.signature.params
        .map((p) => '${p.type} ${p.name}')
        .join(', ');
    final asyncKw = fn.signature.isAsync ? ' async' : '';
    buffer
      ..writeln('  ${fn.signature.returnType} execute($params)$asyncKw {')
      ..writeln('    // Business logic moved from $owner.${fn.name}().');

    final call = _reconstructCall(fn, deps);
    if (call != null) {
      buffer.writeln('    return $call;');
    } else {
      buffer
        ..writeln('    // TODO: move the logic from $owner.${fn.name}() here.')
        ..writeln('    throw UnimplementedError();');
    }
    buffer
      ..writeln('  }')
      ..writeln('}');

    return GeneratedUseCase(
      filePath: _targetPath(fn.filePath, candidate.suggestedFileName),
      content: buffer.toString(),
      candidate: candidate,
    );
  }

  List<ParamInfo> _infraDependencies(BusinessFunction fn) {
    final seen = <String>{};
    final deps = <ParamInfo>[];
    for (final dep in fn.dependencies) {
      if (!InfraTypes.isInfra(dep.type)) continue;
      if (!seen.add(dep.name)) continue;
      deps.add(dep);
    }
    return deps;
  }

  List<String> _referencedTypes(BusinessFunction fn, List<ParamInfo> deps) {
    final types = <String>{
      InfraTypes.baseType(
        fn.signature.returnType,
      ).replaceAll(RegExp(r'^(Future|FutureOr|Stream)$'), ''),
      ...deps.map((d) => InfraTypes.baseType(d.type)),
    }..removeWhere((t) => t.isEmpty || _dartCoreTypes.contains(t));
    return types.isEmpty ? const ['—'] : types.toList();
  }

  /// Reconstructs `<field>.<method>(<args>)` from the function's primary
  /// infrastructure call, or `null` when none is found.
  String? _reconstructCall(BusinessFunction fn, List<ParamInfo> deps) {
    if (deps.isEmpty) return null;
    final depNames = {for (final d in deps) _strip(d.name): d.name};

    for (final c in fn.calls) {
      final receiver = c.receiver;
      if (receiver == null) continue;
      final match = depNames[_strip(receiver)];
      if (match != null) {
        final args = fn.signature.params.map((p) => p.name).join(', ');
        return '$match.${c.target}($args)';
      }
    }
    return null;
  }

  /// Places the UseCase under `<feature>/usecases/` when the source lives in a
  /// `features/<x>/` tree; otherwise beside the source in a `usecases/` folder.
  String _targetPath(String sourceRelPath, String fileName) {
    final path = sourceRelPath.replaceAll(r'\', '/');
    final match = RegExp(r'^(.*?/features/[^/]+)/').firstMatch(path);
    final base = match != null
        ? match.group(1)!
        : path.substring(0, path.lastIndexOf('/').clamp(0, path.length));
    return '$base/usecases/$fileName';
  }

  String _strip(String s) => s.replaceAll('_', '').replaceAll('this.', '');

  String _pascal(String s) {
    final cleaned = s.startsWith('_') ? s.substring(1) : s;
    return cleaned.isEmpty
        ? cleaned
        : cleaned[0].toUpperCase() + cleaned.substring(1);
  }

  static const Set<String> _dartCoreTypes = {
    'void',
    'bool',
    'int',
    'double',
    'num',
    'String',
    'Object',
    'dynamic',
    'List',
    'Map',
    'Set',
    'Future',
    'Stream',
  };
}
