import '../mock_engine/fake_generator.dart';
import '../mock_engine/mock_generator.dart';
import '../models/quality_models.dart';
import 'scenario_library.dart';

/// Synthesizes a test file for a single business function.
///
/// The output is a **compilable scaffold**: real `flutter_test`/`mocktail`
/// imports, a computed import for the class under test, concrete
/// mock/fake declarations, `setUp` wiring, and one `test` per scenario from the
/// [ScenarioLibrary]. Because the unresolved AST can't supply concrete argument
/// values or dependency import paths, the arrange/act/assert bodies are emitted
/// as structured guidance and each generated test is `skip`ped with a reason,
/// so the suite stays green until a developer completes it. Nothing is ever
/// applied to source files — only new test files are proposed.
class TestGenerator {
  TestGenerator({required this.packageName})
    : _mocks = MockGenerator(),
      _fakes = FakeGenerator(),
      _scenarios = ScenarioLibrary();

  /// The project's package name (from pubspec `name:`), used to build the
  /// import for the class under test.
  final String packageName;

  final MockGenerator _mocks;
  final FakeGenerator _fakes;
  final ScenarioLibrary _scenarios;

  GeneratedTestFile generate(BusinessFunction fn) {
    final owner = fn.className ?? _pascal(fn.name);
    final mockSpecs = _mocks.specsFor(fn);
    final fakeSpec = _fakes.specForReturnType(fn.signature.returnType);
    final specs = _scenarios.forReturnType(fn.signature.returnType);
    final returnType = fn.signature.returnType;
    final element = ScenarioLibrary.elementType(returnType);
    final sutImport = _sutImport(fn.filePath);

    final scenarios = <TestScenario>[];
    final buffer = StringBuffer()
      ..writeln('// GENERATED by `relax quality --generate-tests`.')
      ..writeln(
        '// Scaffold only: uncomment the imports/mocks below and remove',
      )
      ..writeln('// the `skip:` markers as you complete each case. Needs the')
      ..writeln('// `mocktail` dev dependency once uncommented.')
      ..writeln("import 'package:flutter_test/flutter_test.dart';")
      ..writeln("// import 'package:mocktail/mocktail.dart';")
      ..writeln('// import $sutImport;');

    if (mockSpecs.isNotEmpty || fakeSpec != null) {
      buffer.writeln();
      for (final m in mockSpecs) {
        buffer.writeln('// ${_mocks.render(m)}');
      }
      if (fakeSpec != null) buffer.writeln('// ${_fakes.render(fakeSpec)}');
    }

    buffer
      ..writeln()
      ..writeln('void main() {');

    if (mockSpecs.isNotEmpty) {
      for (final m in mockSpecs) {
        buffer.writeln(
          '  // late ${m.mockClassName} ${_camel(m.targetClassName)};',
        );
      }
      buffer.writeln('  // late $owner sut;');
      if (fakeSpec != null) {
        buffer
          ..writeln()
          ..writeln('  // setUpAll(() {')
          ..writeln(
            '  //   registerFallbackValue(${fakeSpec.fakeClassName}());',
          )
          ..writeln('  // });');
      }
      buffer
        ..writeln()
        ..writeln('  // setUp(() {');
      for (final m in mockSpecs) {
        buffer.writeln(
          '  //   ${_camel(m.targetClassName)} = ${m.mockClassName}();',
        );
      }
      final ctorArgs = mockSpecs
          .map((m) => _camel(m.targetClassName))
          .join(', ');
      buffer
        ..writeln('  //   sut = $owner($ctorArgs);')
        ..writeln('  // });');
    }

    buffer
      ..writeln()
      ..writeln("  group('$owner.${fn.name}', () {");

    for (final spec in specs) {
      final setup = _setupFor(spec, mockSpecs, fakeSpec);
      final assertion = _assertionFor(spec, fn, element);
      scenarios.add(buildScenario(spec, setup, assertion));

      buffer
        ..writeln("    test('${spec.name}', () async {")
        ..writeln('      // Arrange');
      for (final line in setup.split('\n')) {
        buffer.writeln('      // $line');
      }
      buffer.writeln('      // Act & Assert');
      for (final line in assertion.split('\n')) {
        buffer.writeln('      // $line');
      }
      buffer
        ..writeln("    }, skip: 'relax: complete this generated scaffold');")
        ..writeln();
    }

    buffer
      ..writeln('  });')
      ..writeln('}');

    return GeneratedTestFile(
      filePath: _testPath(fn.filePath),
      content: buffer.toString(),
      scenarios: scenarios,
      businessFunction: fn,
    );
  }

  String _setupFor(ScenarioSpec spec, List<MockSpec> mocks, FakeSpec? fake) {
    if (mocks.isEmpty) return 'No infrastructure dependency detected to mock.';
    final mock = _camel(mocks.first.targetClassName);
    return switch (spec.kind) {
      'success' =>
        fake != null
            ? 'when(() => $mock.<method>(any())).thenAnswer((_) async => ${fake.fakeClassName}());'
            : 'when(() => $mock.<method>(any())).thenAnswer((_) async => <value>);',
      'invalid_input' =>
        'when(() => $mock.<method>(any())).thenThrow(InvalidInputException());',
      'network_error' =>
        "when(() => $mock.<method>(any())).thenThrow(const SocketException('no network'));",
      'server_error' =>
        'when(() => $mock.<method>(any())).thenThrow(ServerException(500));',
      'timeout' =>
        "when(() => $mock.<method>(any())).thenThrow(TimeoutException('timeout'));",
      _ => 'when(() => $mock.<method>(any())).thenAnswer((_) async => null);',
    };
  }

  String _assertionFor(ScenarioSpec spec, BusinessFunction fn, String element) {
    final args = fn.signature.params.map((_) => '<arg>').join(', ');
    final call = 'sut.${fn.name}($args)';
    if (spec.kind == 'success') {
      if (element == 'void' || element.isEmpty) {
        return 'await expectLater($call, completes);';
      }
      return 'final result = await $call;\n'
          'expect(result, isA<$element>());';
    }
    return 'expect(() => $call, throwsA(isA<Exception>()));';
  }

  /// Builds `'package:<pkg>/<path>'` for the class under test.
  String _sutImport(String relPath) {
    final normalized = relPath.replaceAll(r'\', '/');
    final libRelative = normalized.startsWith('lib/')
        ? normalized.substring('lib/'.length)
        : normalized;
    return "'package:$packageName/$libRelative'";
  }

  /// Mirrors the source path under `test/`, replacing `.dart` with `_test.dart`.
  String _testPath(String relPath) {
    final normalized = relPath.replaceAll(r'\', '/');
    final underLib = normalized.startsWith('lib/')
        ? normalized.substring('lib/'.length)
        : normalized;
    final withSuffix = underLib.replaceAll(RegExp(r'\.dart$'), '_test.dart');
    return 'test/$withSuffix';
  }

  String _camel(String s) =>
      s.isEmpty ? s : s[0].toLowerCase() + s.substring(1);

  String _pascal(String s) =>
      s.isEmpty ? s : s[0].toUpperCase() + s.substring(1);
}
